# Server configuration
spring:
  application:
    name: attendance-app-server
  webflux:
    base-path: /api

  # Database configuration
  r2dbc:
    url: r2dbc:postgresql://localhost:54322/finki-services-db
    username: finki_admin
    password: f1nk1_@dm1n

  # Liquibase configuration for local environment
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:54322/finki-services-db
    user: finki_admin
    password: f1nk1_@dm1n
    enabled: false  # Changed from false to true
    contexts: dev,test  # Enable both dev and test contexts
    drop-first: false   # Set to true if you want to drop and recreate schema
    default-schema: public

# Swagger configuration
springdoc:
  api-docs:
    enabled: true

# Logging
logging:
  level:
    liquibase: INFO
    liquibase.changelog: INFO
  pattern:
    console: "%d{ISO8601} [%t] %-5level %logger{36} - %msg%n"