name: attendance_app
description: "Mobile application which verifies student attendance."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  # Storages
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3

  flutter_screenutil: ^5.9.3
  http: ^1.4.0
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.4
  provider: ^6.1.5
  intl: ^0.20.0
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.12.0
  mobile_scanner: ^7.0.0
  device_info_plus: ^11.4.0
  uuid: ^4.5.1
  flutter_blue_plus: ^1.31.18
  logger: ^2.6.1
  shimmer: ^3.0.0
  equatable: ^2.0.5
  url_launcher: ^6.3.2
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/logo/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
